extends: default
rules:
  document-start: disable
  line-length:
    max: 140
    allow-non-breakable-words: true
  new-lines:
    type: unix
  indentation:
    spaces: 2
    indent-sequences: consistent
  trailing-spaces: enable
