# Generated by Django 5.2.1 on 2025-05-09 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interests", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userinterestsrating",
            name="interests",
        ),
        migrations.AddField(
            model_name="userinterestsrating",
            name="interests_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_interests",
                to="interests.interest",
            ),
        ),
    ]
