# Generated by Django 5.2.1 on 2025-05-08 01:37

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="interest_vector",
            field=pgvector.django.vector.VectorField(dimensions=5, null=True),
        ),
    ]
