# Generated by Django 5.2.1 on 2025-05-09 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customuser_interest_vector"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
