# Generated by Django 5.2.1 on 2025-05-16 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_customuser_interest_vector_liked"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserSwipe",
        ),
    ]
