# Generated by Django 5.2.1 on 2025-05-16 14:08

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "users",
            "0006_rejected_date_of_birth_rejected_phone_number_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rejected",
            name="date_of_birth",
        ),
        migrations.RemoveField(
            model_name="rejected",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="rejected",
            name="tg_link",
        ),
        migrations.RemoveField(
            model_name="rejected",
            name="vk_link",
        ),
        migrations.AddField(
            model_name="customuser",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region=None
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="tg_link",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="vk_link",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
