# Generated by Django 5.2.1 on 2025-05-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_remove_rejected_date_of_birth_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_offline",
            field=models.BooleanField(default=False),
        ),
    ]
