# Generated by Django 5.2.2 on 2025-06-09 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_is_offline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_offline',
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(
                blank=True, null=True, upload_to='profiles/%Y/%m/%d/'
            ),
        ),
    ]
