# Generated by Django 5.2.2 on 2025-06-09 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_customuser_is_offline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_offline',
            field=models.BooleanField(default=False),
        ),
    ]
