# Generated by Django 5.2.3 on 2025-06-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_customuser_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='city',
        ),
        migrations.AddField(
            model_name='customuser',
            name='city_name',
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name='Город'
            ),
        ),
    ]
