# Generated by Django 5.2.3 on 2025-06-26 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_customuser_city_customuser_city_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_can_write',
            field=models.BooleanField(default=True),
        ),
    ]
