# Generated by Django 5.2.3 on 2025-06-27 02:25

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_customuser_is_can_write'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='privacy_settings_vector',
            field=pgvector.django.vector.VectorField(
                blank=True, dimensions=9, null=True
            ),
        ),
    ]
