# Generated by Django 5.2.7 on 2025-10-04 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_customuser_privacy_settings_vector'),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE EXTENSION IF NOT EXISTS vector;",
            "DROP EXTENSION IF EXISTS vector;",
        ),
        migrations.RunSQL(
            "CREATE EXTENSION IF NOT EXISTS postgis;",
            "DROP EXTENSION IF EXISTS postgis;",
        ),
    ]
