# Generated by Django 5.2.1 on 2025-05-09 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0002_alter_feedback_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedback",
            name="admin_user",
        ),
        migrations.AddField(
            model_name="feedback",
            name="answered_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата ответа"
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="answered_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="handled_feedbacks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Ответил",
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Создано"
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="text",
            field=models.TextField(verbose_name="Текст отзыва"),
        ),
    ]
