# Generated by Django 5.2.3 on 2025-06-12 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            'feedback',
            '0003_remove_feedback_admin_user_feedback_answered_at_and_more',
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='is_problematic',
        ),
    ]
