# Generated by Django 5.2.3 on 2025-06-12 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_remove_feedback_is_problematic'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='answer_text',
            field=models.TextField(null=True, verbose_name='Текст ответа'),
        ),
    ]
